var Events = {
    MESSAGE: 'MESSAGE_CREATE',
    GUILD: 'GUILD_CREATE',
    SLASH_COMMAND: 'SLASH_COMMAND',
    INTERGATION: 'INTERGATION_CREATE',
    READY: 'READY',
    REACTION_ADD: 'REACTION_ADD',
    REACTION_REMOVE: 'REACTION_REMOVE',
    BUTTON_INTERACTION: 'BUTTON_INTERACTION'
}
Object.freeze(Events)
module.exports = Events;